/**
 * bamboo.ts — BambooHR client.
 *
 * Every call to the HRIS goes through this file. That matters for two reasons:
 * the mock fallback needs exactly one switch rather than a flag threaded
 * through the tool layer, and the mapping from BambooHR's field names to the
 * domain model lives in one auditable place.
 *
 * Auth is HTTP Basic with the API key as username and a literal "x" as the
 * password. The key inherits the permissions of whoever created it, so it must
 * be generated by an account admin to see every employee and field.
 */

import { env } from 'lua-cli';
import { normalizeCountry, type CountryCode } from '../domain/countryRules';

/* -------------------------------------------------------------- config */

const USE_MOCK = (globalThis as { process?: { env?: Record<string, string> } })
  .process?.env?.BAMBOOHR_MOCK === 'true';

function config() {
  return {
    apiKey: env('BAMBOOHR_API_KEY'),
    subdomain: env('BAMBOOHR_SUBDOMAIN'),
    /**
     * Custom-field aliases for the Iqama fields, which do not exist in a
     * stock BambooHR account. Create them under Settings → Custom Fields,
     * then set these to match. Defaults assume the obvious naming.
     */
    iqamaNumberField: env('BAMBOOHR_IQAMA_NUMBER_FIELD') || 'customIqamaNumber',
    iqamaExpiryField: env('BAMBOOHR_IQAMA_EXPIRY_FIELD') || 'customIqamaExpiry',
  };
}

function authHeader(apiKey: string): string {
  // btoa is available in the runtime; Buffer is not guaranteed.
  return `Basic ${btoa(`${apiKey}:x`)}`;
}

function baseUrl(subdomain: string): string {
  return `https://api.bamboohr.com/api/gateway.php/${subdomain}/v1`;
}

/* --------------------------------------------------------------- types */

export interface Employee {
  id: string;
  displayName: string;
  firstName: string;
  lastName: string;
  workEmail?: string;
  mobilePhone?: string;
  jobTitle?: string;
  department?: string;
  supervisor?: string;
  location?: string;

  /** Normalised to an internal code. Null when it cannot be resolved. */
  country: CountryCode | null;
  /** Raw value as BambooHR returned it, kept for error messages. */
  countryRaw?: string;

  hireDate: string;
  monthlyWage?: number;
  basicMonthlyWage?: number;

  iqamaNumber?: string | null;
  iqamaExpiry?: string | null;
}

export interface TimeOffRequest {
  id: string;
  employeeId: string;
  status: string;
  start: string;
  end: string;
  type: string;
  amount?: { unit: string; amount: string };
}

export class BambooError extends Error {
  constructor(
    message: string,
    readonly status?: number,
    readonly endpoint?: string,
  ) {
    super(message);
    this.name = 'BambooError';
  }
}

/* ------------------------------------------------------------- request */

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  const { apiKey, subdomain } = config();

  if (!apiKey || !subdomain) {
    throw new BambooError(
      'BambooHR is not configured. Set BAMBOOHR_API_KEY and BAMBOOHR_SUBDOMAIN.',
    );
  }

  const url = `${baseUrl(subdomain)}${path}`;
  const response = await fetch(url, {
    ...init,
    headers: {
      Authorization: authHeader(apiKey),
      Accept: 'application/json',
      'Content-Type': 'application/json',
      ...(init.headers ?? {}),
    },
  });

  if (response.status === 404) {
    throw new BambooError('Not found in BambooHR.', 404, path);
  }
  if (response.status === 401 || response.status === 403) {
    throw new BambooError(
      'BambooHR rejected the credentials. The API key may lack permission for this record.',
      response.status,
      path,
    );
  }
  if (!response.ok) {
    throw new BambooError(
      `BambooHR returned ${response.status} for ${path}.`,
      response.status,
      path,
    );
  }

  // Some endpoints (time-off submission) return an empty body on success.
  const text = await response.text();
  return (text ? JSON.parse(text) : {}) as T;
}

/* ------------------------------------------------------------- mapping */

const EMPLOYEE_FIELDS = [
  'firstName', 'lastName', 'displayName', 'workEmail', 'jobTitle',
  'department', 'supervisor', 'location', 'country', 'hireDate',
  'customMonthlyWage', 'customBasicWage', 'payRate',
  // Needed to match a WhatsApp number against a personnel record.
  'mobilePhone', 'homePhone', 'workPhone',
];

function toNumber(value: unknown): number | undefined {
  if (value === null || value === undefined || value === '') return undefined;
  const n = Number(String(value).replace(/[^0-9.-]/g, ''));
  return Number.isFinite(n) ? n : undefined;
}

/** Blank strings and BambooHR's "0000-00-00" both mean "not set". */
function toDate(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  if (!trimmed || trimmed.startsWith('0000')) return null;
  return /^\d{4}-\d{2}-\d{2}$/.test(trimmed) ? trimmed : null;
}

function mapEmployee(raw: Record<string, unknown>, cfg = config()): Employee {
  // Country may live on the address field or be inferable from the office location.
  const countryField = typeof raw.country === 'string' ? raw.country.trim() : '';
  const locationField = typeof raw.location === 'string' ? raw.location.trim() : '';

  const countryNormalized = normalizeCountry(countryField);
  const locationNormalized = normalizeCountry(locationField);

  const country = countryNormalized ?? locationNormalized;
  const countryRaw = countryNormalized
    ? countryField
    : (locationNormalized ? locationField : (countryField || locationField || ''));

  return {
    id: String(raw.id ?? ''),
    displayName:
      (raw.displayName as string) ||
      `${raw.firstName ?? ''} ${raw.lastName ?? ''}`.trim(),
    firstName: (raw.firstName as string) ?? '',
    lastName: (raw.lastName as string) ?? '',
    workEmail: (raw.workEmail as string) || undefined,
    mobilePhone: (raw.mobilePhone as string) || (raw.workPhone as string) || undefined,
    jobTitle: (raw.jobTitle as string) || undefined,
    department: (raw.department as string) || undefined,
    supervisor: (raw.supervisor as string) || undefined,
    location: (raw.location as string) || undefined,

    country: normalizeCountry(countryRaw),
    countryRaw: countryRaw || undefined,

    hireDate: toDate(raw.hireDate) ?? '',
    monthlyWage: toNumber(raw.customMonthlyWage ?? raw.payRate),
    basicMonthlyWage: toNumber(raw.customBasicWage),

    iqamaNumber: (raw[cfg.iqamaNumberField] as string) || null,
    iqamaExpiry: toDate(raw[cfg.iqamaExpiryField]),
  };
}

/* --------------------------------------------------------------- calls */

/** Fetch one employee. Throws BambooError(404) when the id is unknown. */
export async function getEmployee(employeeId: string): Promise<Employee> {
  if (USE_MOCK) return mockEmployee(employeeId);

  const cfg = config();
  const fields = [...EMPLOYEE_FIELDS, cfg.iqamaNumberField, cfg.iqamaExpiryField].join(',');
  const raw = await request<Record<string, unknown>>(
    `/employees/${encodeURIComponent(employeeId)}?fields=${fields}`,
  );
  return mapEmployee({ ...raw, id: employeeId }, cfg);
}

/** Fetch the whole roster with Iqama custom fields. Used by the Iqama sweep. */
export async function getDirectory(): Promise<Employee[]> {
  if (USE_MOCK) return MOCK_EMPLOYEES.map((e) => ({ ...e }));

  const cfg = config();
  try {
    const report = await request<{ employees?: Record<string, unknown>[] }>(
      '/reports/custom?format=JSON',
      {
        method: 'POST',
        body: JSON.stringify({
          title: 'Iqama Sweep Roster',
          fields: [
            ...EMPLOYEE_FIELDS,
            cfg.iqamaNumberField,
            cfg.iqamaExpiryField,
            'customMonthlyWage',
          ],
        }),
      },
    );
    if (report.employees && report.employees.length > 0) {
      return report.employees.map((raw) => mapEmployee(raw, cfg));
    }
  } catch {
    // Fall back to standard directory if custom reports are restricted
  }

  const data = await request<{ employees?: Record<string, unknown>[] }>('/employees/directory');
  return (data.employees ?? []).map((raw) => mapEmployee(raw, cfg));
}

/**
 * The people reporting to a given manager.
 *
 * BambooHR stores the supervisor as a display name rather than an id, so this
 * matches on name — case-insensitively, and on surname alone as a fallback,
 * because a team lead typing a check-in writes "Ahmad" not "Ahmad Al-Rashid".
 */
export async function getReports(managerName: string): Promise<Employee[]> {
  const roster = await getDirectory();
  const needle = managerName.trim().toLowerCase();
  if (!needle) return [];

  const exact = roster.filter((e) => e.supervisor?.trim().toLowerCase() === needle);
  if (exact.length) return exact;

  return roster.filter((e) => {
    const supervisor = e.supervisor?.trim().toLowerCase();
    if (!supervisor) return false;
    return supervisor.includes(needle) || needle.includes(supervisor);
  });
}

/** Find employees by name, for resolving a team lead the user named in chat. */
export async function findEmployeesByName(name: string): Promise<Employee[]> {
  const roster = await getDirectory();
  const needle = name.trim().toLowerCase();
  if (!needle) return [];

  return roster.filter((e) => e.displayName?.toLowerCase().includes(needle));
}

/**
 * Time-off type IDs, resolved from the account rather than assumed.
 *
 * These were hardcoded as 1/2/3. That is not a limitation, it is a silent
 * correctness bug: BambooHR numbers time-off types per account, so on any
 * account where sick leave is not id 2, a sick request files as something
 * else and nobody finds out until payroll.
 *
 * Cached for the life of the execution — the mapping does not change mid-turn,
 * and every leave request would otherwise pay for the lookup.
 */
let timeOffTypeCache: Record<string, string> | null = null;

export async function getTimeOffTypeIds(): Promise<Record<string, string>> {
  if (timeOffTypeCache) return timeOffTypeCache;

  const fallback = { annual: '78', sick: '79', unpaid: '83' };
  if (USE_MOCK) return fallback;

  try {
    const types = await request<Array<{ id: string | number; name: string }>>(
      '/meta/time_off/types',
    );

    const list = Array.isArray(types) ? types : (types as { timeOffTypes?: typeof types }).timeOffTypes ?? [];
    const resolved: Record<string, string> = { ...fallback };

    for (const type of list) {
      const name = String(type.name ?? '').toLowerCase();
      const id = String(type.id);

      // Match on meaning, not on exact wording — accounts name these
      // "Annual Leave/Holiday", "Sick", "Unpaid Time Off" and so on.
      if (/annual|vacation|holiday|paid time off|\bpto\b/.test(name)) {
        resolved.annual ??= id;
        if (resolved.annual === fallback.annual) resolved.annual = id;
      } else if (/sick|medical|illness/.test(name)) {
        resolved.sick = id;
      } else if (/unpaid|leave without pay|\blwop\b/.test(name)) {
        resolved.unpaid = id;
      }
    }

    timeOffTypeCache = resolved;
    return resolved;
  } catch {
    // A restricted meta endpoint should not stop someone booking leave.
    return fallback;
  }
}

/** Existing time-off requests, used to compute a committed balance. */
export async function getTimeOffRequests(
  employeeId: string,
  from = '2000-01-01',
  to = '2100-01-01',
): Promise<TimeOffRequest[]> {
  if (USE_MOCK) return [];

  const params = new URLSearchParams({ employeeId, start: from, end: to });
  const data = await request<TimeOffRequest[]>(`/time_off/requests/?${params}`);
  return Array.isArray(data) ? data : [];
}

export interface TimeOffSubmission {
  employeeId: string;
  start: string;
  end: string;
  timeOffTypeId: string | number;
  amount: number;
  note?: string;
}

/** Submit a time-off request. Returns the created request id. */
export async function submitTimeOff(
  input: TimeOffSubmission,
): Promise<{ id: string; status: string }> {
  if (USE_MOCK) {
    return { id: `mock-${Date.now()}`, status: 'requested' };
  }

  const { apiKey, subdomain } = config();
  if (!apiKey || !subdomain) {
    throw new BambooError(
      'BambooHR is not configured. Set BAMBOOHR_API_KEY and BAMBOOHR_SUBDOMAIN.',
    );
  }

  const url = `${baseUrl(subdomain)}/employees/${encodeURIComponent(input.employeeId)}/time_off/request`;
  const response = await fetch(url, {
    method: 'PUT',
    headers: {
      Authorization: authHeader(apiKey),
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      status: 'requested',
      start: input.start,
      end: input.end,
      timeOffTypeId: Number(input.timeOffTypeId) || input.timeOffTypeId,
      amount: input.amount,
      notes: input.note ? [{ from: 'employee', note: input.note }] : undefined,
    }),
  });

  if (!response.ok) {
    throw new BambooError(`BambooHR returned ${response.status} for time_off/request.`, response.status);
  }

  const location = response.headers.get('location') || '';
  const match = location.match(/\/(\d+)$/);
  const id = match ? match[1] : (location || `bamboo-${Date.now()}`);

  return { id, status: 'requested' };
}

/* ---------------------------------------------------------------- mock */

/**
 * Fallback fixtures, used only when BAMBOOHR_MOCK=true.
 *
 * Deliberately spans all four operating countries — the original repo had
 * only KSA and UAE, so the Egyptian and Jordanian rules never ran in a demo.
 * Iqama dates sit in different alert tiers so the sweep has something to find.
 */
const MOCK_EMPLOYEES: Employee[] = [
  {
    id: '1001', displayName: 'Faisal Al-Otaibi', firstName: 'Faisal', lastName: 'Al-Otaibi',
    jobTitle: 'Shift Supervisor', department: 'Operations', location: 'Riyadh, Saudi Arabia',
    country: 'KSA', countryRaw: 'Saudi Arabia',
    hireDate: '2019-02-01', monthlyWage: 12000,
    iqamaNumber: '2• • • • • • • • 1', iqamaExpiry: '2026-09-18',
  },
  {
    id: '1002', displayName: 'Noura Al-Qahtani', firstName: 'Noura', lastName: 'Al-Qahtani',
    jobTitle: 'HR Coordinator', department: 'People', location: 'Riyadh, Saudi Arabia',
    country: 'KSA', countryRaw: 'Saudi Arabia',
    hireDate: '2024-06-15', monthlyWage: 9000,
    iqamaNumber: '2• • • • • • • • 2', iqamaExpiry: '2026-11-30',
  },
  {
    id: '2001', displayName: 'Sara Haddad', firstName: 'Sara', lastName: 'Haddad',
    jobTitle: 'Site Engineer', department: 'Engineering', location: 'Dubai, United Arab Emirates',
    country: 'UAE', countryRaw: 'United Arab Emirates',
    hireDate: '2024-09-15', monthlyWage: 14000, basicMonthlyWage: 8000,
  },
  {
    id: '3001', displayName: 'Mahmoud Fahmy', firstName: 'Mahmoud', lastName: 'Fahmy',
    jobTitle: 'Maintenance Lead', department: 'Operations', location: 'Cairo, Egypt',
    country: 'EGY', countryRaw: 'Egypt',
    hireDate: '2014-03-01', monthlyWage: 22000,
  },
  {
    id: '4001', displayName: 'Rania Odeh', firstName: 'Rania', lastName: 'Odeh',
    jobTitle: 'Logistics Officer', department: 'Supply Chain', location: 'Amman, Jordan',
    country: 'JOR', countryRaw: 'Jordan',
    hireDate: '2022-01-10', monthlyWage: 900,
  },
];

function mockEmployee(employeeId: string): Employee {
  const found = MOCK_EMPLOYEES.find((e) => e.id === employeeId);
  if (!found) throw new BambooError('Not found in BambooHR.', 404);
  return { ...found };
}

export const __mockRoster = MOCK_EMPLOYEES;
